//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ 生成的包含文件。
// 供 Optorun Assistant.rc 使用
//
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDD_OPTORUNASSISTANT_FORM       101
#define IDR_MAINFRAME                   128
#define IDR_OptorunAssistanTYPE         129
#define IDD_OA_VACUUM_FORM              132
#define IDR_OA_FILE_DATA                133
#define IDR_OA_INI_FILE                 134
#define IDR_OA_ENGLISH_LNG              141
#define IDR_OA_CHINESE_LNG              142
#define IDR_OA_CHINESE_LNG_OLD          142
#define IDC_CURSOR_HAND                 143
#define ID_DLG_VACUUM_THREAD_ERROR      144
#define IDI_ICON_PROPERTY               146
#define IDD_DLG_SET_IONGAUGE_MODE       147
#define IDD_DIALIOG_VCC500_SEND_CHAR    149
#define IDD_DLG_EXHAUST_SETUP           151
#define IDD_DIALOG_INIT_VACUUM_TEST     152
#define IDD_DLG_VACUUM_EXHAUST_EDIT     153
#define IDD_OA_ROTATOR_FORM             154
#define IDB_LED_NUMBER                  155
#define IDR_LOGO_GIF                    158
#define IDD_DLG_VACUUM_CURVE_PRO        162
#define IDD_DLG_VACUUM_BG_PRO           164
#define IDD_DLG_VACUUM_ABNOMAL_SETUP    165
#define IDD_DIALIOG_SEND_CHAR           166
#define IDC_ITEM1_SYS_GROUP             1001
#define IDC_STATIC_PLC_STATE            1002
#define IDC_STATIC_PC_NAME              1003
#define IDC_STATIC_MACHINE_TYPE         1004
#define IDC_STATIC_SEQUENCER            1005
#define IDC_STATIC_TOUCHPANEL_VER       1006
#define IDC_EDIT_HISTORY                1007
#define IDC_STATIC_HISTORY              1008
#define IDC_EDIT_HELP_TEXT              1009
#define IDC_STATIC_HELP_TITLE           1010
#define IDC_BUTTON_HELP_LEFT            1011
#define IDC_BUTTON_HELP_RIGHT           1012
#define IDC_BUTTON_CONNECT_PLC          1013
#define IDC_BUTTON_CLOSE_CONNECTION     1014
#define IDC_STATIC_CUR_STATE_TITLE      1015
#define IDC_STATIC_PC_NAME_AREA         1016
#define IDC_STATIC_MACHINE_SN_AREA      1017
#define IDC_STATIC_EXHAUST_GROUP        1017
#define IDC_STATIC_MACHINE_TYPE_AREA    1018
#define IDC_STATIC_LEAK_RATE_GROUP      1018
#define IDC_STATIC_TOUCHPANEL_VER_AREA  1019
#define IDC_EDIT1                       1019
#define IDC_STATIC_PRODUCT_VERSION      1020
#define IDC_STATIC_RECORDER_TEXT        1020
#define IDC_STATIC_OPERATOR_TEXT        1020
#define IDC_STATIC_PRODUCT_VERSION_AREA 1021
#define IDC_STATIC_TEMPERATURE_TEXT     1021
#define IDC_STATIC_EXHUAST_START_TEXT   1022
#define IDC_EDIT2                       1023
#define IDC_EDIT_CHAMBER_VOLUME         1023
#define IDC_STATIC_EXHUAST_START_TEXT2  1024
#define IDC_EDIT3                       1025
#define IDC_EDIT_PRESSURE_KEEP_TIME     1025
#define IDC_STATIC_EXHUAST_START_TEXT3  1026
#define IDC_STATIC_EXHUAST_START_TEXT4  1027
#define IDC_RADIO_DOME_EXSIT            1028
#define IDC_RADIO_DOME_NONE             1029
#define IDC_RADIO1                      1032
#define IDC_RADIO2                      1033
#define IDC_BUTTON_TEST1                1034
#define IDC_BUTTON_TEST2                1035
#define IDC_EDIT_ADDRESS                1036
#define IDC_EDIT_BIT                    1037
#define IDC_STATIC_COMMENT_TEXT         1038
#define IDC_STATIC_PLC_VAC_STATE        1040
#define IDC_CHECK_IONGAUGE              1041
#define IDC_STATIC_PENNING_VALUE_NAME   1042
#define IDC_STATIC_PENNING_VALUE        1043
#define IDC_STATIC_IONGAUGE_VALUE       1044
#define IDC_EDIT_VACUUM_ERROR           1044
#define IDC_BTN_START_VACUUM_TEST       1045
#define IDC_BTN_CANCEL_VACUUM_TEST      1046
#define IDC_EDIT_COMMENT                1048
#define IDC_BTN_IONGAUGE_PROPERTY       1049
#define IDC_BTN_GAUGE_SETUP             1050
#define IDC_RADIO3                      1051
#define IDC_STATIC_SETUP_MODE           1052
#define IDC_CHECK_LEAK_RATE             1053
#define IDC_CHECK_EXHAUST_RATE          1054
#define IDC_RADIO_LEAK_RATE             1059
#define IDC_RADIO_EXHAUST               1060
#define IDC_RADIO_RECORDER              1061
#define IDC_RADIO8                      1062
#define IDC_STATIC_SERIAL_PORT_TEST     1063
#define IDC_BUTTON_COM2_OPEN            1064
#define IDC_BUTTON_COM2_CLOSE           1065
#define IDC_BUTTON_COM2_TEST            1066
#define IDC_BUTTON_COM3_OPEN            1067
#define IDC_BUTTON_COM3_CLOSE           1068
#define IDC_BUTTON_COM3_TEST            1069
#define IDC_BUTTON_COM4_OPEN            1070
#define IDC_BUTTON_COM4_CLOSE           1071
#define IDC_BUTTON_COM4_TEST            1072
#define IDC_BUTTON_COM5_OPEN            1073
#define IDC_BUTTON_COM5_CLOSE           1074
#define IDC_BUTTON_COM5_TEST            1075
#define IDC_COMBO_COM2                  1077
#define IDC_COMBO_COM3                  1078
#define IDC_COMBO_COM4                  1079
#define IDC_COMBO_COM5                  1080
#define IDC_BUTTON_COM2_PROPERTY        1081
#define IDC_BUTTON_COM3_PROPERTY        1082
#define IDC_BUTTON_COM4_PROPERTY        1083
#define IDC_BUTTON_COM5_PROPERTY        1084
#define IDC_STATIC_COM2_TEXT            1085
#define IDC_STATIC_COM3_TEXT            1086
#define IDC_STATIC_COM4_TEXT            1087
#define IDC_STATIC_COM5_TEXT            1088
#define IDC_CHECK_RECORD_VACUUM         1089
#define IDC_COMBO_MACHINE_TYPE          1090
#define IDC_STATIC_COATER_TEXT          1091
#define IDC_CHECK1                      1092
#define IDC_STATIC_TEST_TYPE            1093
#define IDC_CHECK_HEARTH2_DIRECTION     1093
#define IDC_LIST_VACUUM_CONTENT         1094
#define IDC_LIST_VACUUM_CONTENT_EXHAUST 1095
#define IDC_COMBO_INTERVAL              1096
#define IDC_STATIC_INTERVAL_TEXT        1097
#define IDC_STATIC_RECORD_TIME_TEXT     1098
#define IDC_STATIC_ELAPSED_TIME_TEXT    1099
#define IDC_STATIC_ELAPSED_TIME         1100
#define IDC_EDIT_RECORD_TIME            1101
#define IDC_STATIC_PRESSURE_KEEPED_TIME 1101
#define IDC_COMBO_RECORD_TIME           1102
#define IDC_EDIT_EXHUAST_PRESSURE       1103
#define IDC_COMBO_LEAKRATE_START_PRESSURE 1103
#define IDC_STATIC_EXPECT_PRESSURE_TEXT 1104
#define IDC_COMBO_LEAKRATE_KEEP_TIME    1104
#define IDC_STATIC_PRESSURE_KEEP_TIME_TEXT 1105
#define IDC_COMBO_VACUUM_WAIT_TIME      1105
#define IDC_STATIC_EXHAUST_NEED_TIME_TEXT 1106
#define IDC_EDIT_EXHAUST_NEED_TIME      1107
#define IDC_BUTTON_EXHAUST_ST           1108
#define IDC_LIST_EXHAUST                1109
#define IDC_STATIC_EXHAUST_SETUP_HELP_TEXT 1110
#define IDC_STATIC_LEAKRATE_START_PRESSURE_TEXT 1111
#define IDC_EDIT_LEAKRATE_START_PRESSURE 1112
#define IDC_STATIC_WAIT_TIME_TEXT       1113
#define IDC_STATIC_LEAKRATE_WAIT_TIME_TEXT 1113
#define IDC_EDIT_VACUUM_WAIT_TIME       1114
#define IDC_STATIC_CUR_PRESSURE         1115
#define IDC_STATIC_START_PRESSURE       1116
#define IDC_STATIC_PRESSURE_PASS        1117
#define IDC_STATIC_MAX_WAITING_TIME     1118
#define IDC_STATIC_LEAKRATE_KEEP_TIME_TEXT 1119
#define IDC_STATIC_PRESSURE_MIN_KEEP_TIME 1119
#define IDC_EDIT_LEAKRATE_KEEP_TIME     1120
#define IDC_STATIC_STATUS               1121
#define IDC_STATIC_IONGAUGE_TEXT        1122
#define IDC_STATIC_PARAMETERS_GROUP_TEXT 1123
#define IDC_BUTTON_CLEAR_LISTCTRL       1124
#define IDC_CHECK_USING_IONGAUGE        1125
#define IDC_STATIC_USE_IONGAUGE_TEXT    1126
#define IDC_BUTTON_SAVE_LISTCTRL        1127
#define IDC_EDIT_VACUUM_HELP            1128
#define IDC_STATIC_PROGRAM_VERSION      1129
#define IDC_BUTTON_SAVE_LISTCTRL2       1129
#define IDC_STATIC_COMPILE_DATE         1130
#define IDC_BTN_INIT_HEARTH             1131
#define IDC_BUTTON_TEST                 1132
#define IDC_LIST_ROTATOR_CRUCIBLE       1137
#define IDC_BTN_INSERT_HEARTH1          1138
#define IDC_LIST_ROTATOR_DOME           1139
#define IDC_STATIC_HEARTH1_PIC          1149
#define IDC_STATIC_HEARTH2_PIC          1150
#define IDC_BTN_INSERT_HEARTH2          1151
#define IDC_COMBO_HEARTH_1              1152
#define IDC_COMBO_HEARTH_2              1153
#define IDC_BTN_CREATE_HEARTH1          1154
#define IDC_COMBO_HEARTH_12             1155
#define IDC_COMBO_DOME_SPEED            1156
#define IDC_BTN_DELETE_HEARTH_ROW       1157
#define IDC_BTN_START_HEARTH_TEST       1158
#define IDC_BTN_CANCEL_HEARTH_TEST      1159
#define IDC_BTN_SAVE_HEARTH_LIST        1160
#define IDC_CHECK_START_FROM_SELECTION  1161
#define IDC_STATIC_TEST_TIME            1162
#define IDC_BTN_CREATE_HEARTH2          1163
#define IDC_COMBO_HEARTH_22             1164
#define IDC_BTN_DELETE_DOME_ROW         1165
#define IDC_BTN_START_DOME_TEST         1166
#define IDC_STATIC_LOGO                 1167
#define IDC_BTN_CANCEL_DOME_TEST        1167
#define IDC_BTN_STATISTICS_EVALUATION   1168
#define IDC_BTN_SAVE_DOME_LIST          1169
#define IDC_BTN_ADD_VACUUM_FILE         1170
#define IDC_CHECK_START_FROM_SELECTION_DOME 1170
#define IDC_SHIFT_LEFT                  1171
#define IDC_BTN_INSERT_DOME_SPEED       1171
#define IDC_SHIFT_RIGHT                 1172
#define IDC_BTN_AUTOCREATE_DOME_SPEED   1172
#define IDC_BTN_CURVE_PROPERTY          1173
#define IDC_BTN_DELETE_CURVE            1174
#define IDC_COMBO_CURVES                1175
#define IDC_BTN_COLOUR                  1176
#define IDC_SHIFT_LEFT2                 1177
#define IDC_COMBO1                      1177
#define IDC_SHIFT_RIGHT2                1178
#define IDC_COMBO2                      1178
#define IDC_STATIC_PIC                  1179
#define IDC_STATIC_LINE_TEXT            1180
#define IDC_BTN_BG_COLOR                1181
#define IDC_BTN_GRID_COLOR              1182
#define IDC_BTN_SCALE_TEXT_COLOR        1183
#define IDC_EDIT_X_RANGE                1184
#define IDC_EDIT_Y_UPPER_EXP            1185
#define IDC_EDIT_Y_LOWER_EXP            1186
#define IDC_BTN_DEFAULT                 1187
#define IDC_EDIT_X_MINUTES_GRID         1188
#define IDC_CHECK_SHOW_X_GRIDS          1189
#define IDC_COMBO_APC_GAUGE             1190
#define IDC_COMBO_ION_GAUGE             1191
#define IDC_CHECK_HEARTH1_DIRECTION     1193
#define IDC_STATIC_MONITOR_ALERT        1194
#define IDC_STATIC_DOME_HEARTH_SPACE    1195
#define IDC_STATIC_DOME_THREAD_STATE    1196
#define IDC_STATIC_COMMENT              1197
#define IDC_CUSTOM1                     1199
#define ID_VIEW_LANGUAGE                32772
#define ID_LANGUAGE_ENGLISHI            32773
#define ID_LANGUAGE_32774               32774
#define ID_LANGUAGE_SIMPCHN             32775
#define ID_VIEW_XX                      32776
#define ID_VIEW_LANGUAGE32777           32777
#define ID_LANGUAGE_SELECTONE           32778
#define ID_Menu                         32779

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        168
#define _APS_NEXT_COMMAND_VALUE         32780
#define _APS_NEXT_CONTROL_VALUE         1200
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
